### ISSUE TITLE
not function properly on 100% width textarea

### ISSUE THREAD

**Issue by leizard** [ro31337/jquery.ns-autogrow#4] opened 2015-10-29 03:41 UTC
Hi, if my textarea has width:100%, the autogrow does not work properly. It auto expand when I doesn't finish typing all row.
How could I fix that ?
Thank you.

**Comment by leizard** [comment] 2015-10-29 06:52
btw, how could I prevent line break on enter keyup event. Because my textarea is auto-submitted on enter keyup event and I dont want confict.

**Comment by ro31337** [comment] 2015-10-29 16:07
hey @leizard , I'll verify that and will add fixes. I'll add option to skip update if Enter is pressed. If you want quick fix you have to add a check at the beginning of _update_ function. Something like:

```
if event.keyCode is 13
    return
```

**Comment by leizard** [comment] 2015-10-30 02:32
Hi, thank you for your quick reply.
I tried that but seem not work.

```
        update = (function(_this) {
          return function(event) {
           // because sometimes the event is undefined
            if (event) {
               if (event.which === 13) {
                  return;
               }
            }
            var height, val, width;
            val = _this.value.replace(/&/g, ...
```

Where could I be wrong ? 
Thank you

**Comment by leizard** [comment] 2015-10-30 02:45
nah. again. I just forgot to delete the min.js file :D.
It seem solved my issue, which doesn't add one line when I submit a short message (one-line message) any more. But it still expand when I press enter, weird. And If I submit a long message (multi-line message), then clear the textarea value with

```
textarea.val('')
```

The value is clear but it doesn't come back to 'one-line' form, still expand.
How could I fix this. Thank you

**Comment by leizard** [comment] 2015-10-30 02:48
I found something weird. If I debug. It can go to the check statement 

```
 if (event.which === 13) {
     return;
 }           
```

and return properly. But if I don't debug, It act like passing the check statement and still expand with the enter key press

**Comment by ro31337** [comment] 2015-10-30 04:05
Interesting. Can you try returning false? Or try returning false and prevent default like this:

```
 if (event.which === 13) {
     event.preventDefault();
     return false;
 }           
```

**Comment by leizard** [comment] 2015-10-30 05:23
I tried that and it doesn't work right.

```
event.preventDefault();
```

will also prevent my textarea from submiting the value too.

**Comment by cassidylaidlaw** [comment] 2016-02-29 02:37
I'm having the same issue with my textarea at 100% width; it expands too soon.

**Comment by ro31337** [comment] 2016-02-29 02:59
@cassidylaidlaw @leizard can you guys help with reproducing the issue? jsfiddle, plunker, codepen or something plz. Thanks!

Can you guys also check branch [4-width-100-percent-bug](https://github.com/ro31337/jquery.ns-autogrow/tree/4-width-100-percent-bug), `demo` directory. I added example and it seems that it works for me.

**Comment by ro31337** [comment] 2016-03-15 15:44
@cassidylaidlaw @leizard pinging you guys again, can you help with reproducing the issue? Thank you!

**Comment by tuz88** [comment] 2016-07-06 06:25
@ro31337 I seem to have the same issue with the textareas expanding too soon. I've sent you an email to your gmail with details so you can see it

**Comment by jshgyn** [comment] 2016-09-13 17:26
👍 also having an issue with textareas growing at a faster rate than they should

**Comment by ro31337** [comment] 2016-09-13 17:46
@tuz88 @jshgyn please please steps to reproduce, please create repo, or jsfiddle/plunker, anything. Post steps to reproduce and/or create video.

**Comment by tuz88** [comment] 2016-09-14 02:35
Hi Roman - I sent you an email (to roman.pushkin@gmail.com) so you can see it happening - it was sent Jul 6 if you have missed it. I tried to reproduce it elsewhere and couldn't figure out what it was that was causing it to behave like that.

**Comment by ro31337** [comment] 2016-09-28 15:49
@tuz88 thanks, I'm looking at links and they're not available. Can you post here with jsfilddle example so everyone will be able to see and reproduce that?

Thanks!

**Comment by leizard** [comment] 2016-09-29 01:56
hey @ro31337. I'm sorry for not replying recently. It lost track with the project that I used autogrow. Hope someone can reproduce the issue.

**Comment by ro31337** [comment] 2017-08-06 23:12
I'm closing it for now. Let me know if you guys have more info, we'll reopen and fix. Thank you.

**Closed as completed by ro31337** 2017-08-06 23:12 UTC
